[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = ".next"
  prettyURLs = true
  trailingSlash = true
  changeFreq = "monthly"
  priority = 0.5

  # Custom change frequencies
  [[plugins.inputs.customChangeFreq]]
    path = "/"
    changeFreq = "monthly"
  [[plugins.inputs.customChangeFreq]]
    path = "/work"
    changeFreq = "monthly"
  [[plugins.inputs.customChangeFreq]]
    path = "/process"
    changeFreq = "monthly"
  [[plugins.inputs.customChangeFreq]]
    path = "/contact"
    changeFreq = "monthly"
  [[plugins.inputs.customChangeFreq]]
    path = "/blog"
    changeFreq = "weekly"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
