[build]
command = "npm run build"
publish = ".next"

# Sitemap configuration
[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = ".next"
prettyURLs = true
trailingSlash = true
changeFreq = "monthly"
priority = 0.5

# Unfortunately, the plugin doesn't support path-specific configs
# If you need different settings for blog pages, consider using exclude
# and creating a separate sitemap for those specific pages

# Headers configuration for sitemap
[[headers]]
for = "/sitemap.xml"
[headers.values]
Content-Type = "application/xml"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
