[build]
  command = "npm run build"
  publish = ".next"

# Default sitemap configuration
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = ".next"
  prettyURLs = true
  trailingSlash = true
  changeFreq = "monthly"
  priority = 0.5
  exclude = ["/blog/*"]

# Sitemap configuration for /blog
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = ".next"
  prettyURLs = true
  trailingSlash = true
  changeFreq = "weekly"
  priority = 0.5
  include = ["/blog", "/blog/*"]

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
