[build]
command = "npm run build"
publish = ".next"

# Combined sitemap configuration
[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = ".next"
prettyURLs = true
trailingSlash = true

# Default settings for most pages
changeFreq = "monthly"
priority = 0.5

# Special configuration for blog pages
[[plugins.inputs.sitemapPath]]
path = "/blog"
changeFreq = "weekly"
priority = 0.5

[[plugins.inputs.sitemapPath]]
path = "/blog/*"
changeFreq = "weekly"
priority = 0.5

[[headers]]
for = "/sitemap.xml"
[headers.values]
Content-Type = "application/xml"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
